version: '3'
services:
  nginx-proxy:
    build: .
    ports:
      - "5301:443"
    volumes:
      - ./logs:/var/log/nginx  # Map the Nginx log directory to a host directory
      - ./conf.d:/etc/nginx/conf.d  # Map the Nginx configuration directory to a host directory